server:
  port: 8082
  
  

spring:
  application:
    name: Hotel-Service
  datasource:
    #url: jdbc:sqlserver://localhost;databaseName=master;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: Mystrongpass123
    driverClassName: com.mysql.cj.jdbc.Driver
    #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
        
  config:
    import: optional:configserver:http://localhost:8086 
    
  jpa:
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.SQLServerDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

    
  profiles:
    active: dev  
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  